language: php

sudo: false

php:
  - '7.4'
  - nightly

env:
  - DEPENDENCIES=""
  - DEPENDENCIES="--classmap-authoritative"

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES

script:
  - ./vendor/bin/phpunit tests
  - ./vendor/bin/phpcs
